function cardGame() {
  return {
    cardFlipped: false,
    cardsAnswered: 0,
    totalCards: 0,
    selectedCategory: null,
    currentCard: { 
      question: "Click next card to begin", 
      category: "Getting Started" 
    },
    currentCategory: "Getting Started",
    categories: [
      "Bridging Questions",
      "Rights & Responsibilities",
      "Economy & Work",
      "Health & Safety",
      "Environment & Energy",
      "Justice & Community",
      "Tech & Privacy",
      "Foreign Policy & Global Issues",
      "Education & Culture",
      "Government & Institutions"
    ],
    askedQuestions: {}, // Track asked questions by category
    availableQuestions: {}, // Track available questions by category
    allAskedQuestions: new Set(), // Track all asked questions across categories for random mode

    // Political oriented questions from different categories
    questions: [
      {
        category: "Bridging Questions",
        questions: [
          "What's one value you think most people actually share, regardless of politics?",
          "Have you ever changed your mind on an issue? What influenced you?",
          "What's a political stereotype you think is unfair?",
          "Where do you see room for compromise in American politics?",
          "What do you wish the 'other side' understood about your perspective?",
          "What's one issue where you think both sides could cooperate?",
          "Have you ever learned something surprising from someone you disagreed with?",
          "What's one political issue that personally affects your daily life?",
          "What's the difference between healthy debate and destructive argument?",
          "What's one strength you see in people who disagree with you?",
          "Where do you think Americans are more united than divided?",
          "What's one political debate that left you thinking differently?",
          "Do you believe listening is more important than winning an argument? Why?",
          "What role should empathy play in political conversations?",
          "What's one issue you'd like to understand better from another's perspective?",
          "What's a personal experience that shaped your political views?",
          "What issue do you think should not divide people, but often does?",
          "Do you think disagreement is healthy for democracy? Why or why not?",
          "What's one way communities can build more trust across divides?",
          "Have you ever found common ground with someone unexpectedly?",
          "What's one issue you feel everyone should care about?",
          "Do you believe Americans have more in common than differences?",
          "What's a respectful way to disagree with someone?",
          "What's one shared goal most people want for the future?",
          "Do you think polarization is solvable? Why or why not?",
          "What's the fairest ground rule for tough conversations?",
          "When do you feel most open to changing your mind?",
          "What makes you feel heard in a conversation?",
          "What's a time you changed someone else's mind—what worked?",
          "What do you think people misinterpret about your beliefs?",
          "How do you separate facts from opinions when you talk politics?",
          "What makes you trust (or distrust) a source of information?",
          "What's one assumption you try not to make about others?",
          "How do you decide when to speak up and when to listen?",
          "What's a question you'd ask someone who strongly opposes your view?",
          "What does 'good faith' look like in a debate?",
          "What's a time when a compromise felt like a win-win?",
          "How do your life experiences influence your priorities?",
          "What nonpolitical value guides your political opinions?",
          "What's a small step that could improve political dialogue?",
          "How do you respond when a conversation gets heated?",
          "What's a topic you approach with extra humility? Why?",
          "Who is a public figure you disagree with but respect? Why?",
          "What's a local issue that brings people together in your area?",
          "What's the most persuasive argument you've heard from the other side?",
          "How do you know when you've misunderstood someone?",
          "What habit helps you stay curious instead of defensive?",
          "What's a bridge-building phrase you like to use?",
          "What's a belief you hold with low confidence and want to test?",
          "What did your family teach you about handling disagreements?",
          "What's a time you apologized in a political discussion?",
          "What makes a space feel safe for honest conversation?",
          "What's one norm you'd set for this group tonight?",
          "How do you talk about policy without labeling people?",
          "What role should stories play alongside statistics?",
          "What's a time humor helped defuse tension?",
          "How do you avoid 'all-or-nothing' thinking?",
          "What's a value you admire in your opponents' movement?",
          "How has your view matured over the last five years?",
          "What would convince you to revise a long-held belief?",
          "What's a practical way to check your biases?",
          "How do you define 'common good'?",
          "What's a civic ritual that builds unity?",
          "Where do you think language creates unnecessary division?",
          "What's a policy area where you'd trade purity for progress?",
          "How do you handle conversations with family who disagree?",
          "What's a media practice that would improve public discourse?",
          "What's a time you felt genuinely persuaded—and why?",
          "How do you make sure quieter voices are included?",
          "What's a question you wish pundits asked more often?",
          "How do you distinguish between motives and arguments?",
          "What's a political label you avoid and why?",
          "How do you talk about identity without essentializing people?",
          "What's a shared problem we can prototype a solution for tonight?",
          "How do you assess the unintended consequences of policies?",
          "What's a bridge you can build at work or in your neighborhood?",
          "How do you practice steel-manning an opposing view?",
          "What's a time data changed your mind?",
          "How do you keep conversations people-first, not party-first?",
          "What's a 'both/and' idea you like in a polarized debate?",
          "How do you define fairness when values collide?",
          "What's a compromise you could live with on a hot-button issue?",
          "How do you stay engaged without burning out?",
          "What's a source you read that challenges you productively?",
          "How do you handle misinformation from someone you care about?",
          "What's a topic where you think the extremes drown out the middle?",
          "How do you separate short-term wins from long-term goals?",
          "What's one reform to elections that could reduce division?",
          "How do you decide which experts to trust?",
          "What's a community project that sidesteps ideology and helps people?",
          "How do you talk about trade-offs honestly?",
          "What's a time you discovered you were wrong?",
          "How do you stay open when your identity feels challenged?",
          "What's a listening technique that works for you?",
          "How do you encourage nuance on social media?",
          "What's a value you won't compromise—and why?",
          "How do you respond to 'whataboutism'?",
          "What's a bridge-building book, film, or podcast you'd recommend?",
          "How do you keep the humanity of opponents in view?",
          "What's a small norm change that would improve Congress or city hall?"
        ]
      },
      {
        category: "Rights & Responsibilities",
        questions: [
          "Should there be limits to free speech? Why or why not?",
          "What responsibilities come with living in a democracy?",
          "Do you think voting should be mandatory?",
          "Should jury duty remain mandatory?",
          "What’s the role of personal responsibility in society?",
          "What rights do you think are most at risk today?",
          "Should the right to privacy be more protected?",
          "Do Americans have a duty to serve their country in some way?",
          "What’s the balance between individual rights and the common good?",
          "Should people have the right to refuse vaccines?",
          "What rights should be universal regardless of income?",
          "Should there be limits on gun ownership?",
          "What rights should children have?",
          "What’s the government’s role in protecting civil rights?",
          "Should freedom of religion extend to all practices?",
          "Do responsibilities increase with rights?",
          "What civic duties do you think people often ignore?",
          "Should voting age be lowered or raised?",
          "What rights should workers always have?",
          "Should rights ever be suspended during emergencies?",
          "How should society balance rights with security?",
          "What’s one responsibility people overlook as citizens?",
          "Should digital rights be considered human rights?",
          "How should responsibilities be taught to young people?",
          "Should military service be required?",
          "What rights should immigrants have?",
          "Should government protect whistleblowers?",
          "Do corporations have rights like individuals?",
          "Should healthcare be a right or privilege?",
          "How should freedom of the press be protected?",
          "Should people have the right to protest at any time?",
          "What’s the responsibility of citizens in elections?",
          "Should education be considered a right?",
          "What rights come with owning property?",
          "Should social media companies respect free speech?",
          "Do rights vary depending on culture?",
          "Should voting rights ever be revoked?",
          "What’s the duty of parents toward children?",
          "Should people be required to recycle?",
          "What rights should prisoners retain?",
          "Should access to clean water be a right?",
          "What’s the government’s duty during natural disasters?",
          "Should the right to vote apply to non-citizens?",
          "What responsibilities come with freedom of religion?",
          "Should there be limits to property rights?",
          "What’s the role of citizens in protecting democracy?",
          "Should medical care be provided to undocumented immigrants?",
          "Do companies have a duty to protect consumer data?",
          "Should rights differ in times of war?",
          "What’s the responsibility of media in a democracy?",
          "Should internet access be a right?",
          "What rights should people have at work?",
          "Do responsibilities change as technology advances?",
          "Should civic education be mandatory?",
          "What responsibilities come with free speech?",
          "Should governments be required to provide housing?",
          "What’s the role of individuals in protecting the environment?",
          "Should personal data be treated as property?",
          "Do citizens have a duty to be informed?",
          "Should hate speech be protected under free speech?",
          "What rights should elderly people have?",
          "Should healthcare workers have special rights?",
          "What duties come with being part of a community?",
          "Should political donations be considered free speech?",
          "What rights should refugees have?",
          "Do responsibilities grow as societies gain wealth?",
          "Should workers have the right to strike?",
          "Should privacy extend to online activity?",
          "What’s the role of teachers in protecting rights?",
          "Should responsibilities be enforced by law?",
          "Do future generations have rights today?",
          "Should surveillance ever override privacy?",
          "What rights should digital citizens have?",
          "Should governments ensure access to jobs?",
          "What’s the role of religion in defining rights?",
          "Should the right to vote extend to prisoners?",
          "What responsibilities come with citizenship?",
          "Should parents have more rights than schools?",
          "What rights should disabled people be guaranteed?",
          "Should speech online be treated differently?",
          "Do responsibilities vary by age?",
          "Should governments control access to the internet?",
          "What’s one overlooked right in modern times?",
          "Should people have the right to anonymity?",
          "What duties should elected officials always uphold?",
          "Should animals have rights?",
          "Should cultural rights be protected by law?",
          "What responsibilities do tech companies have?",
          "Should the right to assemble be unrestricted?",
          "Do citizens have a duty to serve on juries?",
          "Should safety override individual freedoms?",
          "What rights should children have in education?",
          "Should governments guarantee retirement benefits?",
          "What duties come with freedom of the press?",
          "Should AI respect human rights?",
          "Do global citizens have responsibilities to each other?",
          "Should international law override national rights?",
          "Should climate rights exist?",
          "What responsibilities do leaders owe the people?",
          "Should digital access be free for all?"
        ]
      },
      {
        category: "Economy & Work",
        questions: [
          "Should the minimum wage be a living wage?",
          "What’s the government’s role in reducing poverty?",
          "Should student loans be forgiven?",
          "What’s the future of unions in America?",
          "Is universal basic income a good idea?",
          "What’s the balance between capitalism and fairness?",
          "Should healthcare be tied to employment?",
          "What role should government play in housing affordability?",
          "Should billionaires exist in society?",
          "How should wealth be taxed?",
          "What’s one reform that could make work more fair?",
          "Should companies be required to share profits with workers?",
          "What’s the future of work with automation and AI?",
          "Should tipping culture remain or be replaced with fair wages?",
          "What role should small businesses play in the economy?",
          "Should remote work be a right or a privilege?",
          "How should unemployment benefits be structured?",
          "Should higher education be free or subsidized?",
          "What’s one thing you’d change about the U.S. tax system?",
          "Should workers have more say in company decisions?",
          "What’s the fairest way to handle retirement benefits?",
          "How should America prepare for job loss from technology?",
          "Should trade be free, fair, or restricted?",
          "What role does immigration play in the workforce?",
          "Should the government guarantee every citizen a job?",
          "Should monopolies be broken up?",
          "How should wages be determined?",
          "Should CEOs have salary caps?",
          "What role do ethics play in business?",
          "Should gig workers have the same rights as employees?",
          "How should overtime be compensated?",
          "Should internships be paid?",
          "Should corporations have political influence?",
          "How should we address wage gaps between men and women?",
          "Should stock buybacks be restricted?",
          "How should society value unpaid labor (like caregiving)?",
          "Should retirement age be lowered or raised?",
          "What’s the role of worker cooperatives in the economy?",
          "Should hazardous jobs pay more?",
          "Should government control essential industries?",
          "How should taxes on the wealthy be structured?",
          "Should minimum wage vary by region?",
          "What’s the role of philanthropy in society?",
          "Should there be limits on executive bonuses?",
          "How should society support small farmers?",
          "Should housing be considered a human right?",
          "How should inflation be managed?",
          "Should public transportation be free?",
          "What role should corporations play in social issues?",
          "Should unions have more power?",
          "How should workplace discrimination be addressed?",
          "Should retirement savings be mandatory?",
          "What’s the fairest way to fund Social Security?",
          "Should businesses be responsible for climate impacts?",
          "How should healthcare costs be divided?",
          "Should there be universal childcare?",
          "What’s the role of apprenticeships in education?",
          "Should foreign companies be restricted in U.S. markets?",
          "What’s the role of taxes in promoting equality?",
          "Should remote work be encouraged to cut emissions?",
          "How should gig platforms treat workers?",
          "Should there be a maximum income?",
          "What’s the future of pensions?",
          "Should unions cover gig and freelance workers?",
          "Should robots and AI pay taxes?",
          "How should essential workers be valued?",
          "Should public colleges be tuition-free?",
          "What’s the role of government in creating jobs?",
          "Should taxes fund job retraining programs?",
          "How should wealth inheritance be taxed?",
          "Should part-time workers get full benefits?",
          "What’s the fairest way to tax corporations?",
          "Should employee-owned businesses be incentivized?",
          "How should society respond to mass layoffs?",
          "Should workers be able to vote on company policies?",
          "What’s the role of universal basic income in inequality?",
          "Should government subsidize small businesses?",
          "How should workplace safety be enforced?",
          "Should paid family leave be guaranteed?",
          "Should trade unions be stronger or weaker?",
          "How should industries prepare for automation?",
          "Should companies be forced to publish wage gaps?",
          "What role do taxes play in funding infrastructure?",
          "Should wages be tied to company profits?",
          "How should minimum wage account for inflation?",
          "Should governments regulate the housing market?",
          "Should workweeks be shortened?",
          "How should overtime protections work?",
          "Should employers be taxed for replacing workers with robots?",
          "How should financial literacy be taught?",
          "Should there be limits on corporate lobbying?",
          "What’s the best way to support entrepreneurship?",
          "Should the wealthy have higher voting influence on taxes?",
          "How should unions adapt to remote work?",
          "Should all internships guarantee employment?",
          "What role does dignity play in the workplace?",
          "Should recessions be handled with stimulus or austerity?",
          "How should success in the economy be measured?",
          "Should GDP growth always be a goal?",
          "What’s the future of retirement in America?"
        ]
      },
      {
        category: "Health & Safety",
        questions: [
          "Should healthcare be considered a human right?",
          "How should the U.S. handle mental health care?",
          "Should prescription drugs be price-controlled?",
          "What’s the balance between personal choice and public health?",
          "Should vaccines be required for school attendance?",
          "How should America address the opioid crisis?",
          "Should food labeling be stricter?",
          "What’s the role of government in preventing pandemics?",
          "Should hospitals be public, private, or mixed?",
          "Should guns be regulated for public safety?",
          "What’s the best way to reduce violent crime?",
          "How should emergency response systems improve?",
          "Should smoking be banned entirely?",
          "What role does poverty play in health outcomes?",
          "Should workplace safety laws be stricter?",
          "How should America handle obesity as a health crisis?",
          "Should mental health days be mandatory in schools and jobs?",
          "Should assisted suicide be legalized?",
          "What role should government play in diet and exercise?",
          "How should America prepare for future health crises?",
          "Should health insurance be government-run or private?",
          "Should personal fitness be incentivized?",
          "How should elderly care be handled?",
          "What’s the role of community safety programs?",
          "Should addiction be treated as a crime or a health issue?",
          "What rights should patients always have?",
          "Should vaccines be mandatory for healthcare workers?",
          "How should society treat people with disabilities?",
          "Should police be trained in mental health response?",
          "How should America reduce maternal mortality?",
          "Should alternative medicine be regulated?",
          "What’s the best way to prevent child abuse?",
          "Should there be universal dental care?",
          "How should we address health disparities between communities?",
          "Should organ donation be opt-out by default?",
          "What role should nutrition education play in schools?",
          "How should food deserts be solved?",
          "Should the government ban harmful chemicals in products?",
          "How should America handle homelessness as a health crisis?",
          "Should mental health care be free?",
          "How should drug overdoses be prevented?",
          "Should police or medics respond to overdoses?",
          "What’s the role of technology in healthcare?",
          "Should AI be trusted in medical diagnoses?",
          "How should medical malpractice be handled?",
          "Should there be universal vision and hearing care?",
          "What’s the best way to reduce traffic accidents?",
          "Should seatbelt laws be stricter?",
          "How should pedestrian and cyclist safety improve?",
          "Should opioids be more tightly controlled?",
          "How should prisons handle inmate healthcare?",
          "Should schools have nurses full time?",
          "What’s the role of health education in preventing crises?",
          "Should personal health data be private or shareable?",
          "How should society support caregivers?",
          "Should fast food be more regulated?",
          "What’s the best way to lower healthcare costs?",
          "Should employers cover mental health services?",
          "How should the U.S. prepare for climate-related health risks?",
          "Should gym memberships be tax-deductible?",
          "Should alcohol sales be more restricted?",
          "How should gun violence be treated as a public health issue?",
          "Should children be required to have regular checkups?",
          "What’s the role of peer support in mental health?",
          "Should public parks and gyms be government-funded?",
          "How should bullying in schools be prevented?",
          "Should ambulance rides be free?",
          "How should infectious diseases be reported?",
          "Should anti-vaccine misinformation be restricted?",
          "How should crisis hotlines be expanded?",
          "What’s the best way to reduce suicides?",
          "Should mental health be prioritized over incarceration?",
          "Should addiction recovery be government-funded?",
          "How should natural disaster preparedness improve?",
          "Should hospitals be nonprofit only?",
          "What role does diet play in long-term health?",
          "Should doctors be required to disclose costs upfront?",
          "How should rural communities get better healthcare access?",
          "Should healthcare workers be paid more?",
          "How should child nutrition programs expand?",
          "Should sugary cereals be banned for kids?",
          "How should school lunches be improved?",
          "Should violent video games be considered a safety issue?",
          "How should domestic violence victims be better protected?",
          "Should self-defense be taught in schools?",
          "What’s the role of community centers in safety?",
          "Should pharmacies provide free health checks?",
          "How should teen drug use be reduced?",
          "Should vaping be banned like smoking?",
          "What role do stress and work culture play in health?",
          "Should sleep be considered a public health issue?",
          "How should America handle long COVID?",
          "Should people have the right to refuse lifesaving care?",
          "How should nursing shortages be addressed?",
          "Should public health officials be elected?",
          "What role should schools play in mental health care?",
          "Should universal paid sick leave exist?",
          "How should we protect healthcare workers from violence?",
          "Should diet-related diseases be covered differently?",
          "How should society prepare for aging populations?"
        ]
      },
      {
        category: "Environment & Energy",
        questions: [
          "Should the U.S. invest more in renewable energy?",
          "What’s the role of nuclear energy in the future?",
          "Should fossil fuels be phased out?",
          "How should America handle climate refugees?",
          "What’s the best way to protect endangered species?",
          "Should plastic be banned or limited?",
          "How should America handle recycling better?",
          "Should electric cars be subsidized?",
          "What’s the role of farming in climate change?",
          "Should factory farming be restricted?",
          "How should forests and parks be protected?",
          "Should water use be taxed or regulated?",
          "What’s the role of corporations in reducing pollution?",
          "Should climate change denial be tolerated in policy?",
          "How should cities prepare for climate disasters?",
          "Should homeowners be rewarded for going green?",
          "Should energy be publicly owned or private?",
          "What’s one thing individuals can do to help the planet?",
          "Should drilling in national parks be banned?",
          "What role should international cooperation play in climate policy?",
          "Should air travel be limited for climate reasons?",
          "How should America balance jobs with environmental protection?",
          "Should clean water be a constitutional right?",
          "Should solar and wind power replace fossil fuels?",
          "How should young people influence climate policy?",
          "Should single-use plastics be banned nationwide?",
          "What’s the role of oceans in fighting climate change?",
          "Should fracking be legal?",
          "How should America reduce carbon emissions?",
          "Should the U.S. rejoin and strengthen global climate agreements?",
          "What’s the fairest way to handle carbon taxes?",
          "Should cities ban gas-powered cars?",
          "What’s the role of indigenous knowledge in climate solutions?",
          "Should companies pay for their carbon footprint?",
          "How should public transportation be improved for the climate?",
          "Should people be rewarded for reducing waste?",
          "What role should schools play in teaching sustainability?",
          "Should bottled water be banned?",
          "How should we reduce ocean plastic?",
          "Should government invest in climate tech innovation?",
          "What’s the role of geoengineering in climate change?",
          "Should extreme polluters face criminal charges?",
          "How should renewable energy jobs be created?",
          "Should deforestation be treated as a global crime?",
          "What’s the role of rooftop solar in communities?",
          "Should air conditioners be regulated for energy use?",
          "How should climate migration be supported?",
          "Should oil companies be held financially responsible for climate change?",
          "What role should climate lawsuits play?",
          "Should environmental education be mandatory?",
          "How should endangered habitats be restored?",
          "Should cars be taxed based on emissions?",
          "What role does overconsumption play in climate change?",
          "Should meat consumption be reduced for the environment?",
          "How should food waste be solved?",
          "Should homes be required to meet green standards?",
          "What’s the role of international trade in emissions?",
          "Should plastic straws be banned?",
          "How should energy grids be modernized?",
          "Should climate change be declared a national emergency?",
          "What’s the role of citizen activism in energy policy?",
          "Should corporations be rated on sustainability?",
          "How should natural disasters be funded?",
          "Should the government fund green infrastructure?",
          "What’s the role of community gardens in climate resilience?",
          "Should fertilizers and pesticides be regulated more?",
          "How should air quality be improved?",
          "Should recycling be mandatory?",
          "What’s the best way to cut methane emissions?",
          "Should fossil fuel subsidies be eliminated?",
          "What role does population growth play in sustainability?",
          "Should international flights be taxed for emissions?",
          "How should renewable energy storage improve?",
          "Should wind farms be built offshore?",
          "What’s the role of wildlife corridors in conservation?",
          "Should climate misinformation be restricted?",
          "How should climate risks be built into insurance?",
          "Should plastic packaging be banned?",
          "What’s the role of hydrogen energy?",
          "Should companies publish sustainability reports?",
          "How should eco-tourism be regulated?",
          "Should people pay for using excess water?",
          "What’s the role of soil health in the environment?",
          "Should lawns be replaced with native plants?",
          "How should coastal flooding be addressed?",
          "Should climate education be part of every degree?",
          "What role should faith groups play in climate action?",
          "Should oil drilling offshore be banned?",
          "How should energy poverty be solved?",
          "Should cities be required to have climate plans?",
          "Should renewable energy be cheaper than fossil fuels?",
          "How should America protect pollinators like bees?",
          "What’s the role of innovation vs conservation?",
          "Should corporations offset emissions or reduce them directly?",
          "How should climate change shape foreign policy?",
          "Should local communities control their own energy?",
          "What’s the role of public art in raising climate awareness?",
          "Should extreme weather victims be compensated by government?",
          "How should future generations’ rights be protected?",
          "Should climate goals be legally binding?"
        ]
      },
      {
        category: "Justice & Community",
        questions: [
          "Should policing be reformed or reimagined?",
          "How should prisons be structured?",
          "Should the death penalty be abolished?",
          "What’s the role of community programs in reducing crime?",
          "Should marijuana be legalized nationwide?",
          "What’s the fairest way to handle bail?",
          "Should felons regain voting rights?",
          "How should the justice system handle juveniles?",
          "What’s the role of rehabilitation vs punishment?",
          "Should body cameras be required for all police?",
          "What’s the best way to reduce gun violence?",
          "Should hate crimes have harsher penalties?",
          "What’s the role of communities in preventing crime?",
          "Should immigration laws be stricter or looser?",
          "How should refugees be treated in America?",
          "Should undocumented immigrants have a path to citizenship?",
          "How should America handle homelessness?",
          "What’s the fairest way to handle protests?",
          "Should non-violent drug offenders be released?",
          "How should systemic racism be addressed?",
          "Should private prisons be abolished?",
          "What’s the role of federal vs local law enforcement?",
          "Should neighborhoods have more say in policing?",
          "What’s the role of trust in community safety?",
          "How should justice be taught in schools?",
          "Should solitary confinement be banned?",
          "How should ex-convicts reintegrate into society?",
          "Should police unions have less power?",
          "What’s the role of restorative justice?",
          "Should ICE be abolished or reformed?",
          "How should domestic violence cases be handled?",
          "Should jury trials be required for all cases?",
          "How should hate speech be treated legally?",
          "Should facial recognition be used in law enforcement?",
          "What’s the role of citizen oversight in policing?",
          "Should cash bail be eliminated?",
          "How should sexual assault cases be handled?",
          "Should prisons focus more on education and job training?",
          "What’s the fairest way to sentence crimes?",
          "Should youth offenders be tried as adults?",
          "How should America prevent wrongful convictions?",
          "Should for-profit bail bonds exist?",
          "What role should mental health play in sentencing?",
          "Should police carry non-lethal weapons only?",
          "What’s the role of community policing?",
          "Should sanctuary cities exist?",
          "How should immigration detention be improved?",
          "Should immigration judges be independent?",
          "What role should churches play in helping communities?",
          "Should police budgets be cut or increased?",
          "How should mass incarceration be reduced?",
          "Should police have military equipment?",
          "What’s the role of public defenders?",
          "Should jury duty be paid fairly?",
          "How should hate crimes be prevented?",
          "Should graffiti be punished or seen as art?",
          "What role does poverty play in crime?",
          "Should loitering laws exist?",
          "How should shoplifting be treated?",
          "Should immigration courts be expanded?",
          "What’s the role of citizen advocacy groups?",
          "Should neighborhoods have community watch programs?",
          "How should homelessness be decriminalized?",
          "Should curfews for teens exist?",
          "What role do schools play in preventing crime?",
          "Should drug use be treated as a medical issue?",
          "How should reentry programs for prisoners be funded?",
          "Should all police wear body cams?",
          "What role should juries play in sentencing?",
          "Should undocumented immigrants be deported for minor crimes?",
          "How should child abuse be prosecuted?",
          "Should protests ever be restricted?",
          "What’s the fairest way to handle looting?",
          "Should sanctuary campuses exist?",
          "How should racial profiling be eliminated?",
          "Should stop-and-frisk be legal?",
          "What’s the role of transparency in policing?",
          "Should prison labor be paid fairly?",
          "How should violent offenders be rehabilitated?",
          "Should restorative justice replace trials?",
          "What’s the role of voting in building trust?",
          "Should mental illness reduce sentencing?",
          "How should gun offenders be sentenced?",
          "Should police be tested for bias?",
          "What’s the role of youth mentorship in crime prevention?",
          "Should hate crime laws cover more groups?",
          "How should America handle mass shootings?",
          "Should immigrants in detention have legal aid?",
          "What’s the role of trust in jury decisions?",
          "Should sexual harassment be criminalized more strongly?",
          "How should elder abuse be handled?",
          "Should immigration raids be limited?",
          "What role should federal law play in policing reforms?",
          "Should restorative circles replace punishments in schools?",
          "Should neighborhoods vote on policing policies?",
          "What’s the fairest way to handle trespassing?",
          "How should youth crime prevention be expanded?",
          "Should community mediation replace minor courts?",
          "What’s the role of forgiveness in justice?",
          "Should immigration detainees be treated as refugees?"
        ]
      },
      {
        category: "Tech & Privacy",
        questions: [
          "Should tech companies be regulated more?",
          "How should the U.S. handle online misinformation?",
          "Should social media companies ban political ads?",
          "What’s the role of AI in society?",
          "Should people have the right to delete their online data?",
          "Should government surveillance be limited?",
          "How should kids’ screen time be managed?",
          "Should facial recognition be banned?",
          "What’s the role of technology in education?",
          "Should internet access be a basic right?",
          "What’s the impact of social media on democracy?",
          "Should companies be fined for data breaches?",
          "Should online anonymity be protected?",
          "What’s the future of digital currency?",
          "Should influencers be regulated like media?",
          "How should America prepare for cyberwarfare?",
          "Should employers monitor employees online?",
          "What’s the role of algorithms in shaping society?",
          "Should deepfakes be illegal?",
          "How should tech monopolies be handled?",
          "Should kids use smartphones in school?",
          "What’s the role of tech in public safety?",
          "Should people profit from their own data?",
          "What’s the role of privacy in healthcare tech?",
          "Should there be a right to disconnect from work?",
          "Should AI decisions be transparent?",
          "How should online bullying be prevented?",
          "Should virtual reality be regulated?",
          "What role does technology play in mental health?",
          "Should personal devices be taxed for recycling?",
          "How should tech companies handle harmful content?",
          "Should biometric data be private?",
          "What role should encryption play in privacy?",
          "Should smart home devices be regulated?",
          "How should the U.S. handle digital identity?",
          "Should governments own critical tech infrastructure?",
          "What’s the role of open-source technology?",
          "Should AI art be considered theft?",
          "How should companies handle AI bias?",
          "Should children’s data be more protected?",
          "What’s the role of blockchain in society?",
          "Should autonomous vehicles be legal everywhere?",
          "How should online scams be stopped?",
          "Should drones be regulated for privacy?",
          "What role should big tech play in elections?",
          "Should governments ban addictive app designs?",
          "How should wearable devices handle health data?",
          "Should robots replace human jobs?",
          "What’s the role of free speech on the internet?",
          "Should government control social media platforms?",
          "How should online marketplaces be regulated?",
          "Should schools ban phones in classrooms?",
          "What’s the role of parental controls online?",
          "Should hackers who expose flaws be rewarded?",
          "How should misinformation be fact-checked?",
          "Should AI be used in policing?",
          "What’s the role of digital libraries?",
          "Should user data be treated as property?",
          "How should tech be taxed?",
          "Should children under 13 be banned from social media?",
          "What role should anonymity play in democracy?",
          "Should cloud storage be government regulated?",
          "How should virtual money be taxed?",
          "Should governments break up large tech companies?",
          "What’s the role of citizen privacy in surveillance?",
          "Should location tracking be banned?",
          "How should app stores be regulated?",
          "Should video game loot boxes be banned?",
          "What’s the role of digital literacy in schools?",
          "Should smart cities be encouraged?",
          "How should online hate speech be handled?",
          "Should biometric passports be required?",
          "What role should non-profits play in tech?",
          "Should public Wi-Fi be free?",
          "How should streaming platforms be regulated?",
          "Should people have the right to be forgotten?",
          "What’s the role of AI in healthcare?",
          "Should tech addiction be considered a public health issue?",
          "How should gig economy apps be regulated?",
          "Should online voting be allowed?",
          "What’s the role of open internet access?",
          "Should cyberattacks be treated as terrorism?",
          "How should privacy be protected in smart cars?",
          "Should digital IDs replace driver’s licenses?",
          "What role should tech play in disaster response?",
          "Should parental consent be required for kids online?",
          "How should facial recognition be limited?",
          "Should AI be allowed to make life-or-death decisions?",
          "What’s the role of quantum computing in security?",
          "Should online platforms verify all users?",
          "How should workplace tech surveillance be limited?",
          "Should VR worlds have laws?",
          "What’s the role of ethical hacking?",
          "Should deepfake creators be punished?",
          "How should dating apps handle privacy?",
          "Should smart devices share data with police?",
          "What’s the role of tech in bridging inequality?",
          "Should AI replace judges in minor cases?",
          "Should digital monopolies be banned?",
          "What’s the role of civil rights in cyberspace?"
        ]
      },
      {
        category: "Foreign Policy & Global Issues",
        questions: [
          "Should America intervene in foreign conflicts?",
          "What’s the role of the U.S. in the United Nations?",
          "Should foreign aid be increased or decreased?",
          "How should America handle global pandemics?",
          "Should the U.S. be the 'world’s police'?",
          "What’s the role of NATO today?",
          "How should America handle refugees?",
          "What’s the role of trade agreements in the economy?",
          "Should America bring manufacturing back home?",
          "How should America respond to global climate change?",
          "Should foreign governments be allowed to own U.S. companies?",
          "What’s the role of diplomacy vs military power?",
          "Should America spend less on the military?",
          "What’s the role of sanctions in foreign policy?",
          "Should the U.S. work more closely with allies?",
          "What’s the role of foreign policy in human rights?",
          "Should America accept more asylum seekers?",
          "How should the U.S. handle rising global powers like China?",
          "What’s the role of America in space exploration?",
          "Should global internet be a shared resource?",
          "How should America address terrorism abroad?",
          "Should America reduce its nuclear weapons?",
          "What’s the role of the U.S. in global poverty?",
          "Should Americans care more about global issues?",
          "How should America respond to Russian aggression?",
          "Should foreign policy prioritize democracy or stability?",
          "What’s the role of cultural exchange in diplomacy?",
          "Should America withdraw troops overseas?",
          "How should America prevent cyberattacks from abroad?",
          "Should humanitarian intervention be mandatory?",
          "What’s the role of global institutions in conflict?",
          "Should the U.S. defend Taiwan?",
          "How should America handle North Korea?",
          "Should sanctions punish governments or protect citizens?",
          "What’s the role of embassies in diplomacy today?",
          "Should foreign aid be tied to human rights?",
          "How should America handle international arms sales?",
          "Should America rebuild war-torn countries?",
          "What’s the role of technology in foreign relations?",
          "Should climate change drive foreign policy?",
          "How should America handle foreign propaganda?",
          "Should the U.S. cooperate more with the EU?",
          "What’s the role of peacekeeping troops?",
          "Should America lead or follow on global issues?",
          "How should immigration policy reflect global crises?",
          "Should America join more international treaties?",
          "What’s the role of intelligence agencies in foreign affairs?",
          "Should the U.S. expand its military presence abroad?",
          "How should global pandemics be coordinated?",
          "Should foreign aid focus on health or infrastructure?",
          "What’s the role of soft power in diplomacy?",
          "Should America recognize more disputed nations?",
          "How should the U.S. handle global corruption?",
          "Should America forgive debts of poor nations?",
          "What’s the role of technology in global inequality?",
          "Should global water rights be negotiated?",
          "How should America engage in the Middle East?",
          "Should peace talks include non-state actors?",
          "What’s the role of international law?",
          "Should America lead on global internet freedom?",
          "How should America prevent nuclear proliferation?",
          "Should humanitarian visas be expanded?",
          "What’s the role of education in global stability?",
          "Should the U.S. host more refugees?",
          "How should America respond to failed states?",
          "Should aid be prioritized for democracies?",
          "What’s the role of climate refugees in policy?",
          "Should global trade be more regulated?",
          "How should America handle foreign cybercrime?",
          "Should space exploration be international?",
          "What’s the role of the World Health Organization?",
          "Should foreign aid go to allies first?",
          "How should the U.S. rebuild alliances?",
          "Should America promote religious freedom abroad?",
          "What’s the role of sanctions in deterring war?",
          "Should foreign military bases be closed?",
          "How should America handle global disinformation?",
          "Should peace talks include ordinary citizens?",
          "What’s the role of women in foreign policy?",
          "Should international courts have more power?",
          "How should America protect global human rights activists?",
          "Should the U.S. give more to global climate funds?",
          "What’s the role of cultural diplomacy?",
          "Should foreign oil dependence end?",
          "How should America handle global migration?",
          "Should America mediate in African conflicts?",
          "What’s the role of language in diplomacy?",
          "Should America reform the UN Security Council?",
          "How should the U.S. handle disputed borders?",
          "Should humanitarian aid bypass corrupt governments?",
          "Should America stop selling arms abroad?",
          "How should America rebuild trust globally?",
          "Should global tech standards be shared?",
          "What’s the role of corporations in foreign policy?",
          "Should America ban foreign political donations?",
          "How should the U.S. address global inequality?",
          "Should foreign aid include climate adaptation?",
          "What’s the role of young leaders in foreign affairs?",
          "Should America prioritize peace or economic gain?",
          "How should global cooperation be taught?"
        ]
      },
      {
        category: "Education & Culture",
        questions: [
          "Should college be free or affordable for everyone?",
          "What’s the role of standardized testing?",
          "Should school curriculums teach more civics?",
          "How should history be taught in schools?",
          "Should religion have a place in public schools?",
          "What’s the role of arts education?",
          "Should student debt be forgiven?",
          "What’s the role of parents in education?",
          "Should school start times be later?",
          "What’s the role of culture in shaping politics?",
          "Should controversial books be banned in schools?",
          "How should sex education be taught?",
          "What’s the role of technology in classrooms?",
          "Should schools focus more on trades than college?",
          "What’s the role of diversity in education?",
          "Should school lunches be free?",
          "How should cultural holidays be respected?",
          "Should media literacy be taught in schools?",
          "What’s the role of social media in shaping culture?",
          "Should public funding support museums and libraries?",
          "What’s the role of teachers’ unions?",
          "Should schools teach more about global cultures?",
          "What’s the role of sports in education?",
          "Should homeschooling be more regulated?",
          "How should America handle cultural division?",
          "Should foreign languages be required in schools?",
          "What’s the role of teachers in shaping values?",
          "Should schools teach financial literacy?",
          "How should schools handle bullying?",
          "Should art and music be core subjects?",
          "What’s the role of cultural exchange programs?",
          "Should college admissions consider race or class?",
          "How should schools teach about climate change?",
          "Should parents decide school curriculums?",
          "What’s the role of libraries in the digital age?",
          "Should education be the same across states?",
          "How should cultural heritage be preserved?",
          "Should private schools get public funding?",
          "What’s the role of teachers in democracy?",
          "Should public schools have uniforms?",
          "How should schools adapt to technology?",
          "Should extracurriculars be publicly funded?",
          "What’s the role of storytelling in culture?",
          "Should schools teach indigenous history?",
          "How should schools promote tolerance?",
          "Should sex education be abstinence-only?",
          "What’s the role of universities in innovation?",
          "Should school be year-round?",
          "How should schools measure success?",
          "Should parents have vouchers for schools?",
          "What’s the role of culture in identity?",
          "Should public schools teach religion academically?",
          "How should schools prepare students for work?",
          "Should homework be eliminated?",
          "What’s the role of teachers in mental health?",
          "Should college athletes be paid?",
          "How should schools handle book censorship?",
          "Should schools teach coding early?",
          "What’s the role of cultural festivals?",
          "Should schools have mental health counselors?",
          "Should schools teach philosophy?",
          "What’s the role of documentaries in education?",
          "Should museums be free?",
          "How should schools prepare for AI?",
          "Should schools teach emotional intelligence?",
          "What’s the role of music in culture?",
          "Should foreign exchange be free?",
          "How should parents be involved in school boards?",
          "Should student voices guide education policy?",
          "What’s the role of film in shaping culture?",
          "Should schools ban cell phones?",
          "How should schools handle diverse religions?",
          "Should financial aid be expanded?",
          "What’s the role of teachers as mentors?",
          "Should college entrance exams be abolished?",
          "How should schools support immigrants?",
          "Should recess be mandatory?",
          "What’s the role of social studies today?",
          "Should public broadcasting be funded?",
          "How should schools protect LGBTQ+ students?",
          "Should education focus more on creativity?",
          "What’s the role of folklore in culture?",
          "How should schools use digital textbooks?",
          "Should cultural appropriation be taught?",
          "What’s the role of sports in culture?",
          "Should arts programs be required?",
          "How should rural schools be supported?",
          "What’s the role of parents in homework?",
          "Should school cafeterias serve local food?",
          "How should schools teach consent?",
          "Should charter schools be expanded?",
          "What’s the role of literature in culture?",
          "Should cultural stereotypes be challenged in schools?",
          "How should schools handle misinformation?",
          "Should online learning replace classrooms?",
          "What’s the role of poetry in culture?",
          "Should college majors be more flexible?",
          "How should schools support creativity?",
          "Should schools teach current events?",
          "Should teachers be paid more?"
        ]
      },
      {
        category: "Government & Institutions",
        questions: [
          "Should the Electoral College be abolished?",
          "What’s the role of the Supreme Court in modern times?",
          "Should campaign finance be reformed?",
          "What’s the role of lobbying in government?",
          "Should term limits exist for Congress?",
          "How should the balance of power be maintained?",
          "Should voting be easier or stricter?",
          "What’s the role of political parties today?",
          "Should gerrymandering be illegal?",
          "How should corruption be prevented?",
          "Should government officials be held to stricter ethics?",
          "What’s the role of federal vs state power?",
          "Should D.C. and Puerto Rico become states?",
          "How should elections be funded?",
          "What’s the role of government in protecting democracy?",
          "Should Supreme Court justices have term limits?",
          "How should power transitions be safeguarded?",
          "Should presidents have more or less power?",
          "What’s the role of government in technology?",
          "Should there be stricter rules on conflicts of interest?",
          "How should transparency be enforced?",
          "Should there be national service requirements?",
          "What’s the role of government in disaster response?",
          "Should political ads be regulated?",
          "How should trust in government be restored?",
          "Should congressional salaries be capped?",
          "What’s the role of executive orders?",
          "Should voting be a national holiday?",
          "How should redistricting be handled?",
          "Should the Senate filibuster be abolished?",
          "What’s the role of state constitutions?",
          "Should Supreme Court decisions be binding forever?",
          "How should impeachment be handled?",
          "Should presidents be allowed unlimited executive orders?",
          "What’s the role of checks and balances?",
          "Should voting machines be replaced with paper ballots?",
          "How should whistleblowers be protected?",
          "Should Congress have age or health limits?",
          "What’s the role of independent agencies?",
          "Should presidential pardons be limited?",
          "How should judges be appointed?",
          "Should the two-party system be replaced?",
          "What’s the role of the Census?",
          "Should voting districts reflect communities?",
          "How should emergency powers be limited?",
          "Should government shutdowns be legal?",
          "What’s the role of inspectors general?",
          "Should treaties require more oversight?",
          "How should classified information be handled?",
          "Should politicians have financial transparency?",
          "What’s the role of state governors?",
          "Should presidents serve one longer term instead of two?",
          "How should succession crises be managed?",
          "Should Congress expand in size?",
          "What’s the role of state legislatures?",
          "Should lobbying be banned?",
          "How should ethics in government be enforced?",
          "Should Supreme Court rulings need supermajorities?",
          "What’s the role of federal agencies?",
          "Should recall elections be expanded?",
          "How should voter suppression be prevented?",
          "Should campaign ads disclose funding sources?",
          "What’s the role of local government?",
          "Should government contracts be transparent?",
          "How should foreign influence in elections be prevented?",
          "Should Cabinet members require more scrutiny?",
          "What’s the role of watchdog groups?",
          "Should election day be extended to a week?",
          "How should presidential debates be run?",
          "Should political parties control primaries?",
          "What’s the role of the Justice Department?",
          "Should filibuster reform happen?",
          "How should succession for Congress be handled?",
          "Should state courts follow federal precedent?",
          "What’s the role of government in free speech?",
          "Should ranked-choice voting be national?",
          "How should political corruption be punished?",
          "Should presidents be immune from lawsuits?",
          "What’s the role of executive privilege?",
          "Should Supreme Court cameras be allowed?",
          "How should dark money in politics be handled?",
          "Should voter ID be required?",
          "What’s the role of state constitutions in rights?",
          "Should federal judges be elected?",
          "How should new states be admitted?",
          "Should voting age be changed?",
          "What’s the role of Congress in war?",
          "Should government regulate social media?",
          "How should separation of church and state be protected?",
          "Should senators be term-limited?",
          "What’s the role of bureaucracy?",
          "Should presidents appoint more judges?",
          "How should judicial ethics be enforced?",
          "Should politicians face recall votes nationally?",
          "What’s the role of transparency in government?",
          "Should presidential veto power be limited?",
          "How should succession in disasters be handled?",
          "Should constitutional amendments be easier?",
          "What’s the role of the people in government reform?",
          "Should government be more decentralized?",
          "How should election security be guaranteed?",
          "Should trust in media be tied to government?",
          "What’s the role of accountability in democracy?"
        ]
      }
    ],

    init() {
      // Initialize tracking of asked and available questions
      this.questions.forEach(category => {
        this.askedQuestions[category.category] = [];
        this.availableQuestions[category.category] = [...category.questions];
      });
      
      // Calculate total cards
      this.totalCards = this.questions.reduce((total, category) => total + category.questions.length, 0);
    },

    flipCard() {
      if (this.currentCard.question !== "Click next card to begin") {
        this.cardFlipped = !this.cardFlipped;
      }
    },

    selectCategory(category) {
      this.selectedCategory = this.selectedCategory === category ? null : category;
    },

    nextCard() {
      let availableCategories = this.questions;
      
      // If a category is selected, filter to only that category
      if (this.selectedCategory) {
        availableCategories = this.questions.filter(cat => cat.category === this.selectedCategory);
      }
      
      // Filter categories that still have available questions
      availableCategories = availableCategories.filter(cat => 
        this.availableQuestions[cat.category].length > 0
      );
      
      // If no questions are available, show message and return
      if (availableCategories.length === 0) {
        this.currentCard = {
          category: "All Done!",
          question: "You've answered all available questions in " + 
                   (this.selectedCategory ? this.selectedCategory : "all categories") + 
                   ". Reset the game or select a different category."
        };
        this.currentCategory = "All Done!";
        this.cardFlipped = true;
        return;
      }
      
      // Select a random category from available ones
      const categoryIndex = Math.floor(Math.random() * availableCategories.length);
      const category = availableCategories[categoryIndex];
      
      // Select a random question from available questions in that category
      const questionIndex = Math.floor(Math.random() * this.availableQuestions[category.category].length);
      const question = this.availableQuestions[category.category][questionIndex];
      
      // Update asked and available questions
      this.askedQuestions[category.category].push(question);
      this.availableQuestions[category.category] = this.availableQuestions[category.category]
        .filter(q => q !== question);
      
      // Add to global asked questions set for random mode
      this.allAskedQuestions.add(question);
      
      this.currentCard = {
        category: category.category,
        question: question
      };
      
      this.currentCategory = category.category;
      this.cardsAnswered++;
      
      this.cardFlipped = true;
    },

    resetGame() {
      this.cardFlipped = false;
      this.cardsAnswered = 0;
      this.selectedCategory = null;
      this.currentCard = { 
        question: "Click next card to begin", 
        category: "Getting Started" 
      };
      this.currentCategory = "Getting Started";
      this.resetTracking();
    },
    
    resetTracking() {
      // Reset tracking of asked and available questions
      this.questions.forEach(category => {
        this.askedQuestions[category.category] = [];
        this.availableQuestions[category.category] = [...category.questions];
      });
      this.allAskedQuestions.clear();
    },
    
    getCategoryProgress(categoryName) {
      const category = this.questions.find(cat => cat.category === categoryName);
      if (!category) return { answered: 0, total: 0 };
      
      return {
        answered: this.askedQuestions[categoryName].length,
        total: category.questions.length
      };
    }
  }
}